// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: data_provider_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_data_provider_service_proto protoreflect.FileDescriptor

const file_data_provider_service_proto_rawDesc = "" +
	"\n" +
	"\x1bdata_provider_service.proto\x12\x02v1\x1a\tapi.proto\x1a\x1bgoogle/protobuf/empty.proto2\x84\x02\n" +
	"\x13DataProviderService\x12;\n" +
	"\n" +
	"SearchTask\x12\x15.v1.SearchTaskRequest\x1a\x16.v1.SearchTaskResponse\x12;\n" +
	"\n" +
	"CreateTask\x12\x15.v1.CreateTaskRequest\x1a\x16.v1.CreateTaskResponse\x122\n" +
	"\aGetTask\x12\x12.v1.GetTaskRequest\x1a\x13.v1.GetTaskResponse\x12?\n" +
	"\fUpdateStatus\x12\x17.v1.UpdateStatusRequest\x1a\x16.google.protobuf.EmptyB9Z7github.com/task-resolver/task-resolver-pkg/grpc-api/v1/b\x06proto3"

var file_data_provider_service_proto_goTypes = []any{
	(*SearchTaskRequest)(nil),   // 0: v1.SearchTaskRequest
	(*CreateTaskRequest)(nil),   // 1: v1.CreateTaskRequest
	(*GetTaskRequest)(nil),      // 2: v1.GetTaskRequest
	(*UpdateStatusRequest)(nil), // 3: v1.UpdateStatusRequest
	(*SearchTaskResponse)(nil),  // 4: v1.SearchTaskResponse
	(*CreateTaskResponse)(nil),  // 5: v1.CreateTaskResponse
	(*GetTaskResponse)(nil),     // 6: v1.GetTaskResponse
	(*emptypb.Empty)(nil),       // 7: google.protobuf.Empty
}
var file_data_provider_service_proto_depIdxs = []int32{
	0, // 0: v1.DataProviderService.SearchTask:input_type -> v1.SearchTaskRequest
	1, // 1: v1.DataProviderService.CreateTask:input_type -> v1.CreateTaskRequest
	2, // 2: v1.DataProviderService.GetTask:input_type -> v1.GetTaskRequest
	3, // 3: v1.DataProviderService.UpdateStatus:input_type -> v1.UpdateStatusRequest
	4, // 4: v1.DataProviderService.SearchTask:output_type -> v1.SearchTaskResponse
	5, // 5: v1.DataProviderService.CreateTask:output_type -> v1.CreateTaskResponse
	6, // 6: v1.DataProviderService.GetTask:output_type -> v1.GetTaskResponse
	7, // 7: v1.DataProviderService.UpdateStatus:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_provider_service_proto_init() }
func file_data_provider_service_proto_init() {
	if File_data_provider_service_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_provider_service_proto_rawDesc), len(file_data_provider_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_provider_service_proto_goTypes,
		DependencyIndexes: file_data_provider_service_proto_depIdxs,
	}.Build()
	File_data_provider_service_proto = out.File
	file_data_provider_service_proto_goTypes = nil
	file_data_provider_service_proto_depIdxs = nil
}
