// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: difficulty.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Difficulty int32

const (
	Difficulty_UNSPECIFIED Difficulty = 0
	Difficulty_EASY        Difficulty = 1
	Difficulty_NORMAL      Difficulty = 2
	Difficulty_HARD        Difficulty = 3
)

// Enum value maps for Difficulty.
var (
	Difficulty_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "EASY",
		2: "NORMAL",
		3: "HARD",
	}
	Difficulty_value = map[string]int32{
		"UNSPECIFIED": 0,
		"EASY":        1,
		"NORMAL":      2,
		"HARD":        3,
	}
)

func (x Difficulty) Enum() *Difficulty {
	p := new(Difficulty)
	*p = x
	return p
}

func (x Difficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Difficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_difficulty_proto_enumTypes[0].Descriptor()
}

func (Difficulty) Type() protoreflect.EnumType {
	return &file_difficulty_proto_enumTypes[0]
}

func (x Difficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Difficulty.Descriptor instead.
func (Difficulty) EnumDescriptor() ([]byte, []int) {
	return file_difficulty_proto_rawDescGZIP(), []int{0}
}

var File_difficulty_proto protoreflect.FileDescriptor

const file_difficulty_proto_rawDesc = "" +
	"\n" +
	"\x10difficulty.proto\x12\x02v1*=\n" +
	"\n" +
	"Difficulty\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\b\n" +
	"\x04EASY\x10\x01\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x02\x12\b\n" +
	"\x04HARD\x10\x03B9Z7github.com/task-resolver/task-resolver-pkg/grpc-api/v1/b\x06proto3"

var (
	file_difficulty_proto_rawDescOnce sync.Once
	file_difficulty_proto_rawDescData []byte
)

func file_difficulty_proto_rawDescGZIP() []byte {
	file_difficulty_proto_rawDescOnce.Do(func() {
		file_difficulty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_difficulty_proto_rawDesc), len(file_difficulty_proto_rawDesc)))
	})
	return file_difficulty_proto_rawDescData
}

var file_difficulty_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_difficulty_proto_goTypes = []any{
	(Difficulty)(0), // 0: v1.Difficulty
}
var file_difficulty_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_difficulty_proto_init() }
func file_difficulty_proto_init() {
	if File_difficulty_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_difficulty_proto_rawDesc), len(file_difficulty_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_difficulty_proto_goTypes,
		DependencyIndexes: file_difficulty_proto_depIdxs,
		EnumInfos:         file_difficulty_proto_enumTypes,
	}.Build()
	File_difficulty_proto = out.File
	file_difficulty_proto_goTypes = nil
	file_difficulty_proto_depIdxs = nil
}
