// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: status_value.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusValue int32

const (
	StatusValue_STATUS_UNSPECIFIED StatusValue = 0
	StatusValue_STATUS_CREATED     StatusValue = 1
	StatusValue_STATUS_PENDING     StatusValue = 2
	StatusValue_STATUS_INPROGRESS  StatusValue = 3
	StatusValue_STATUS_DONE        StatusValue = 4
)

// Enum value maps for StatusValue.
var (
	StatusValue_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_CREATED",
		2: "STATUS_PENDING",
		3: "STATUS_INPROGRESS",
		4: "STATUS_DONE",
	}
	StatusValue_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_CREATED":     1,
		"STATUS_PENDING":     2,
		"STATUS_INPROGRESS":  3,
		"STATUS_DONE":        4,
	}
)

func (x StatusValue) Enum() *StatusValue {
	p := new(StatusValue)
	*p = x
	return p
}

func (x StatusValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusValue) Descriptor() protoreflect.EnumDescriptor {
	return file_status_value_proto_enumTypes[0].Descriptor()
}

func (StatusValue) Type() protoreflect.EnumType {
	return &file_status_value_proto_enumTypes[0]
}

func (x StatusValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusValue.Descriptor instead.
func (StatusValue) EnumDescriptor() ([]byte, []int) {
	return file_status_value_proto_rawDescGZIP(), []int{0}
}

var File_status_value_proto protoreflect.FileDescriptor

const file_status_value_proto_rawDesc = "" +
	"\n" +
	"\x12status_value.proto\x12\x02v1*u\n" +
	"\vStatusValue\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_CREATED\x10\x01\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x02\x12\x15\n" +
	"\x11STATUS_INPROGRESS\x10\x03\x12\x0f\n" +
	"\vSTATUS_DONE\x10\x04B9Z7github.com/task-resolver/task-resolver-pkg/grpc-api/v1/b\x06proto3"

var (
	file_status_value_proto_rawDescOnce sync.Once
	file_status_value_proto_rawDescData []byte
)

func file_status_value_proto_rawDescGZIP() []byte {
	file_status_value_proto_rawDescOnce.Do(func() {
		file_status_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_value_proto_rawDesc), len(file_status_value_proto_rawDesc)))
	})
	return file_status_value_proto_rawDescData
}

var file_status_value_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_status_value_proto_goTypes = []any{
	(StatusValue)(0), // 0: v1.StatusValue
}
var file_status_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_status_value_proto_init() }
func file_status_value_proto_init() {
	if File_status_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_value_proto_rawDesc), len(file_status_value_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_status_value_proto_goTypes,
		DependencyIndexes: file_status_value_proto_depIdxs,
		EnumInfos:         file_status_value_proto_enumTypes,
	}.Build()
	File_status_value_proto = out.File
	file_status_value_proto_goTypes = nil
	file_status_value_proto_depIdxs = nil
}
